### ISSUE TITLE
P1部件名称与实际不一致

### ISSUE THREAD

**Issue by opants** [inf-labs/INF_BlackHole2#1]
P1部件底部写的是PPM,但世界是接PWM接收机的，是不是部件底部错吧“PWM"写成了”PPM“??
Blackhole1 & Blackhole2都是这样

**Comment by StrHero** [comment]
是的，应该是PWM，原理图标记有点小错误

**Comment by opants** [comment]
Blackhole2的电路图我看上面没有PMM接收机的接口，是取消对PMM接收机的支持了吗？

**Comment by StrHero** [comment]
PPM支持的，PWM是硬件六通道，PPM只需要使用其中的一个硬件通道就可以了，只是读取的协议不一样而已，黑洞2代码目前还没增加PPM读取代码，完全可以自己加入。
