### ISSUE TITLE
MOS是否需要接续流二极管

### ISSUE THREAD

**Issue by opants** [inf-labs/INF_BlackHole2#3]
我看了1&2代原理图，里面MOS都没有接续流二极管，为什么不用接？对MOS有没有特别要求？我选定的MOS是AO3416，有没有问题？

**Comment by StrHero** [comment]
可以不用接，你选用的我们不知道是啥

**Comment by opants** [comment]
那你们推荐的MOS是什么型号

发自我的 iPhone

**Comment by StrHero** [comment]
建议是用NMOS，型号：00BF
